name: test

on:
  workflow_call:
    branches: [ bla ]
    inputs:
      node_version:
        description: 'node version'
        default: '14'
        type: string
      something:
        description: 'node version'
        default: '14'
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret
        run: echo ${{ inputs.something }} | base64
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ inputs.node_version }}
      # - run: npm install
      # - run: npm test
